name: bedtools_nuc
description: Profiles the nucleotide content of intervals in a fasta file.
keywords:
  - bed
  - fasta
  - composition
tools:
  - bedtools:
      description: A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
      homepage: https://bedtools.readthedocs.io
      documentation: https://bedtools.readthedocs.io/en/latest/content/tools/makewindows.html
      doi: "10.1093/bioinformatics/btq033"
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: Bed feature file
      pattern: "*.{bed}"
  - fasta:
      type: file
      description: Input fasta file
      pattern: "*.{fa,fasta}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bed:
      type: file
      description: BED file containing the windows
      pattern: "*.bed"
authors:
  - "@joshuamschmidt"
maintainers:
  - "@kevbrick"