name: "bcftools_cnv"
description: Copy number variation caller, requires a VCF annotated with the Illumina’s B-allele frequency (BAF) and Log R Ratio intensity (LRR) values.
keywords:
  - cnv
tools:
  - "cnv":
      description: "opy number variation caller, requires a VCF annotated with the Illumina’s B-allele frequency (BAF) and Log R Ratio intensity (LRR) values."
      homepage: https://samtools.github.io/bcftools
      documentation: https://samtools.github.io/bcftools/howtos/cnv-calling.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bcf:
      type: file
      description: BCF file
      pattern: "*.{bcf}"
  - af_file:
      type: file
      description: "Read allele frequencies from a tab-delimited file containing the columns: CHROM\tPOS\tREF,ALT\tAF."
  - af_file_tbi:
      type: file
      description: "tbi index of af_file."
  - genetic_map:
      type: file
      description: "Genetic map in the format required also by IMPUTE2."
  - regions_file:
      type: file
      description: "Regions can be specified either on command line or in a VCF, BED, or tab-delimited file (the default)."
  - samples_file:
      type: file
      description: "File of sample names to include or exclude if prefixed with '^'."
  - targets_file:
      type: file
      description: "Targets can be specified either on command line or in a VCF, BED, or tab-delimited file (the default)."
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - roh:
      type: file
      description: Contains site-specific and/or per-region runs of homo/autozygosity calls.
      pattern: "*.{roh}"
authors:
  - "@ramprasadn"
maintainers:
  - "@ramprasadn"